### ISSUE TITLE
Wrong url in templates

### ISSUE THREAD

**Issue by Matth--** [toughdeveloper/oc-imageresizer-plugin#24] opened 2017-08-26 21:34 UTC
When using the ```|resize(X,X)``` filter the url generated in the template uses the following structure
![image](https://user-images.githubusercontent.com/5814301/29745283-cfb651ee-8ab6-11e7-8b56-db36f26be0bd.png)

But when I look at the stored image it uses the following structure:
![image](https://user-images.githubusercontent.com/5814301/29745285-e4f46b68-8ab6-11e7-9150-93884b7eb3d5.png)

I got it working by changing the code in Image.php
```php
/**
     * Generates a thumbnail filename.
     * @return string
     */
    protected function getThumbFilename($width, $height)
    {
        $width = (integer) $width;
        $height = (integer) $height;
        
        return 'thumb__' . $width . 'x' . $height . '_' . $this->options['offset'][0] . '_' . $this->options['offset'][1] . '_' . $this->options['mode'] . '.' . $this->options['extension'];
    }
```

with

```php
/**
     * Generates a thumbnail filename.
     * @return string
     */
    protected function getThumbFilename($width, $height)
    {
        $width = (integer) $width;
        $height = (integer) $height;
        
        return 'thumb__' . $width . '_' . $height . '_' . $this->options['offset'][0] . '_' . $this->options['offset'][1] . '_' . $this->options['mode'] . '.' . $this->options['extension'];
    }
```

**Comment by machinecodeblue** [comment] 2017-09-12 15:09
I was here to point out the same issue.  Otherwise, this is a great plug-in

**Comment by toughdeveloper** [comment] 2017-09-15 07:22
Sorry for the delay with this, just put a response on another open issue (https://github.com/toughdeveloper/oc-imageresizer-plugin/issues/25) but will be putting some time into this over the weekend so a fix should be ready ASAP. Thanks for your help.

**Comment by machinecodeblue** [comment] 2017-09-15 11:20
I think it's line 2:20 or something it requires the removal of the ex with
an underscore a very simple fix

**Comment by gabrieleciech** [comment] 2017-11-09 11:14
I'm using the latest version of OctoberCMS (427) and also the latest version of this plugin but the problem is still there. When will be the fix published?

**Comment by machinecodeblue** [comment] 2017-11-09 11:39
Yes I'm not quite certain why this problem has not been fixed, it's an
excellent plugin otherwise.

**Comment by toughdeveloper** [comment] 2017-11-17 08:11
Closing as resolved with https://github.com/toughdeveloper/oc-imageresizer-plugin/issues/25

**Closed by toughdeveloper** 2017-11-17 08:11 UTC
